name: task
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  google_fonts: ^5.1.0
  equatable: ^2.0.5
  go_router: ^10.1.2
  flutter_bloc: ^8.1.3

  freezed: ^2.4.1
  freezed_annotation: ^2.4.1

  json_annotation: ^4.8.1

  get_it: ^7.6.4

  dio: ^5.3.2
  retrofit: ^4.0.1

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8

  json_serializable: ^6.7.1

  # testing
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  mocktail_image_network: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
